name: dev-cd.yml

on:
  push:
    branches: ["develop"]
    paths:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build project
        run: ./gradlew clean build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/crew-wiki:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/crew-wiki:${{ github.sha }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SERVER_EIP }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key: ${{ secrets.DEV_SERVER_PEM }}
          script: |
            set -euo pipefail
            BASE_DIR=/home/ubuntu/crew-wiki
            IMG=${{ secrets.DOCKERHUB_USERNAME }}/crew-wiki:latest

            sudo mkdir -p "$BASE_DIR"
            sudo tee "$BASE_DIR/.env" >/dev/null <<'EOF'
            LOG_PATH=${{ secrets.LOG_PATH }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            JWT_SECRET_EXPIRE_LENGTH=${{ secrets.JWT_SECRET_EXPIRE_LENGTH }}
            DEV_DB_URL=${{ secrets.DEV_DB_URL }}
            DEV_DB_USERNAME=${{ secrets.DEV_DB_USERNAME }}
            DEV_DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}
            AWS_CREDENTIALS_ACCESS_KEY=${{ secrets.AWS_CREDENTIALS_ACCESS_KEY }}
            AWS_CREDENTIALS_SECRET_KEY=${{ secrets.AWS_CREDENTIALS_SECRET_KEY }}
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            EOF

            sudo docker rm -f crew-wiki || true
            sudo docker pull "$IMG"
            
            sudo docker run -d \
            --name crew-wiki \
            --env-file "$BASE_DIR/.env" \
            -p 8080:8080 \
            "$IMG"
