name: dev-cd.yml

on:
  push:
    branches: [ "develop" ]
    paths:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
        working-directory: ./

      - name: Build project
        run: ./gradlew clean build
        working-directory: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/crew-wiki:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/crew-wiki:${{ github.sha }}

      - name: Create/Update .env for container
        run: |
          cat <<EOF > ~/crew-wiki/.env
          LOG_PATH=${{ secrets.LOG_PATH }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          JWT_SECRET_EXPIRE_LENGTH=${{ secrets.JWT_SECRET_EXPIRE_LENGTH }}
          DEV_DB_URL=${{ secrets.DEV_DB_URL }}
          DEV_DB_USERNAME=${{ secrets.DEV_DB_USERNAME }}
          DEV_DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}
          AWS_CREDENTIALS_ACCESS_KEY=${{ secrets.AWS_CREDENTIALS_ACCESS_KEY }}
          AWS_CREDENTIALS_SECRET_KEY=${{ secrets.AWS_CREDENTIALS_SECRET_KEY }}
          S3_BUCKET=${{ secrets.S3_BUCKET }}
          EOF

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SERVER_EIP }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key: ${{ secrets.DEV_SERVER_PEM }}
          script: |
            sudo docker stop crew-wiki || true
            sudo docker rm crew-wiki || true

            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/crew-wiki:latest

            echo "LOG_PATH=${{ secrets.LOG_PATH }}" > ~/crew-wiki/.env

            sudo docker run -d \
                --name crew-wiki \
                -v ${{ github.workspace }}/config:/app/config \
                -p 8081:8080 \
                ${{ secrets.DOCKERHUB_USERNAME }}/crew-wiki:latest
